-- Comandos DLL --
CREATE DATABASE DELIVERY LACTH;

CREATE TABLE Produto(
    ID_PRODUTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR (255) NOT NULL,
    Preco DECIMAL (9,2),
    Status BOOLEAN DEFAULT FALSE
);

CREATE TABLE FORMA_PAGAMENTO(
    ID FORMA_PAGAMENTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PAGAMENTO_ENTREGA DEFAULT TRUE,
    DINHEIRO BOOLEAN DEFAULT TRUE,
    CARTAO BOOLEAN DEFAULT FALSE,   
);


CREATE TABLE CLIENTE(
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID FORMA_PAGAMENTO NOT NULL
    NOME VARCHAR(255) NOT NULL,
    TELEFONE DECIMAL(11,0),
    ENDERECO VARCHA(255) NOT NULL,
    STATUS BOOLEAN DEFAULT TRUE,
    FOREIGN KEY(ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO)
);

CREATE TABLE ENTREGADOR(
    ID_ENTREGADOR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHA(255) NOT NULL,
    CPF DECIMAL (11,0) NOT NULL,
    TELEFONE (11,0),
    DISPONIVEL BOOLEAN,
);

CREATE TABLE PEDIDO(
    ID_PEDIDO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VALOR,
    ID_CLIENTE,
    ID_PRODUTO,
    ID_ENTREGADOR
);


-- CREATE TABLE NUTRICIONISTA(
--     ID_NURICIONISTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     NOME VARCHAR(200),
--     FORMACAO NOT NULL VARCHAR(500),
-- );

-- CREATE TABLE DIAGNOSTICO(
--     ID_DIAGNOSTICO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     ID_NURICIONISTA INT NOT NULL,
--     ID_CLIENTE INT NOT NULL,
--     DESCRICAO VARCHAR(500),
--     FOREIGN KEY(ID) REFERENCES NUTRICIONISTA(ID)
-- );

-- IDEIA PRO STATUS CLIENTE, 
-- caso fique uns 5 anos sem utilizar colocar automaticamente status false
-- quando ele for usar novamente pedir atualização de dados como endereço e telefone