-- COMANDOS DLL ESTRUTURA DE BANCO DE DADOS DO MERCADO

CREATE DATABASE MERCADO;

CREATE TABLE MERCADO.PRODUTO(
    ID_PRODUTO INT AUTO INCREMENT NOT NULL PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    PRECO DECIMAL (9,2),
    STATUS BOOLEAN DEAFAULT TRUE
);
CREATE TABLE MERCADO.CLIENTE(
    ID_CLIENTE INT AUTO INCREMENT NOT NULL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(25),
    STATUS BOOLEAN DEFAULT TRUE
);
CREATE TABLE MERCADO.PEDIDO(
    ID_PEDIDO INT AUTO INCREMENT NOT NULL PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID),
    ID_CLIENTE INT NOT NULL, 
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    QUANTIDADE INT,
    TOTAL DECIMAL (9,2)
);
